#!/bin/sh // serve para inicializar o codigo
while read input_text // condicao de comando enquanto
do // fazer oque esta abaixo
  case $input_text in // nao sei essa
        hello)          echo English    ;; // escrever o idioma ingles quando for escrito ola neste idioma
        howdy)          echo American   ;; // escrever o idioma americanoquando for escrito neste idioma
        gday)           echo Australian ;; // escrever o idioma australia  quando for escrito ola neste idioma
        bonjour)        echo French     ;; // escrever o idioma frances for escrito ola neste idioma
        "guten tag")    echo German     ;; // escrever o idioma alemao for escrito ola neste idioma
        *)              echo Unknown Language: $input_text // exibir na tela lingua desconhecida
                ;; // pular uma linha
   esac // nao sei essa tbm
done ​< myfile.txt // finalizar o que foi pedido
